### ISSUE TITLE
chore: use factories in tests

### ISSUE THREAD

**Issue by lilsweetcaligula** [OpenPromisesProject/api#105]
Before we may improve test coverage, we may need to DRY up the way we initialize our fixtures in tests. A factory package seems like a good way to do so.

**Comment by nazreen** [comment]
reading this now, I am more averse to adding more dependencies..

**Comment by nazreen** [comment]
can you give an example of where a factory would be useful?

**Comment by nazreen** [comment]
closing stale issues. can reopen if will be worked on
