### ISSUE TITLE
when developing on local, firebase auth should not be necessary

### ISSUE THREAD

**Issue by nazreen** [OpenPromisesProject/api#141]
when developing and testing API requests, it will always need firebase auth

maybe we can exempt it from requiring firebase auth tokens when running on localhost

@lilsweetcaligula what do you think?

**Comment by lilsweetcaligula** [comment]
Yes, we should certainly completely decouple the testing environment from the Google Cloud. This will guard us against potential accidents during the development process.

**Comment by nazreen** [comment]
the complete decoupling will be the larger mission. this issue is specific to disabling the auth side. I will take it as agreement then :)

**Comment by nazreen** [comment]
@lilsweetcaligula what do you think would be the best way to solve this issue?

**Comment by nazreen** [comment]
closing this, but also, a dev firebase project has been created. anyone who needs it, ask me
